# Site settings
title: Gabriele Barni's personal page
email: barn.gab@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  I will add more stuff, this is just a test, we'll see how it goes ...
baseurl: ""
url: "http://localhost:4000"
github_username:  burnout87

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
