# Site settings
title: Gabriele Barni's personal page
email: barn.gab@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  I will add more stuff, this is just a test, we'll see how it goes ...
# baseurl: ""
url: "https://github.com/burnout"
github_username:  burnout87
linkedin_username: barnigabriele

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
